version: '3.7'

services:
  api:
    build: ./service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./service/:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pg
      - POSTGRES_DB=pg
volumes:
  postgres_data: